/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IJasmineEATExtensions,
  IJasmineEATExtensionsInterface,
} from "../../../src/interfaces/IJasmineEATExtensions";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "frozen",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IJasmineEATExtensions__factory {
  static readonly abi = _abi;
  static createInterface(): IJasmineEATExtensionsInterface {
    return new utils.Interface(_abi) as IJasmineEATExtensionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJasmineEATExtensions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IJasmineEATExtensions;
  }
}
