/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IJasmineOracle,
  IJasmineOracleInterface,
} from "../../../src/interfaces/IJasmineOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "encodedMetadata",
        type: "bytes",
      },
    ],
    name: "updateSeries",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IJasmineOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IJasmineOracleInterface {
    return new utils.Interface(_abi) as IJasmineOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJasmineOracle {
    return new Contract(address, _abi, signerOrProvider) as IJasmineOracle;
  }
}
